export const servicesContent = [
  {
    id: 1,
    delay: 400,
    t1: "Responsive",
    t2: "Design",
    subt: "Responsive design allows your website content to flow freely across all screen resolutions and sizes, and renders it to look great on all devices.",
    icon: "bx bx-slideshow services__icon",
    modal1: "Design for thumb",
    modal2: "Leverage mobile devices native hardware",
    modal3: "Keep the typography responsive",
  },
  {
    id: 2,
    delay: 400,
    t1: "Clean",
    t2: "Code",
    subt: "The way of writing code such that the code is easily readable, testable, and less prone to errors.",
    icon: "bx bx-code-alt services__icon",
    modal1: "Easier to maintain",
    modal2: "Easier to understand",
    modal3: "Easier for search engines to understand",
  },
  {
    id: 3,
    delay: 500,
    t1: "UX",
    t2: "Design",
    subt: "UX design focuses on building products that someone can easily use and enjoy using.",
    icon: "bx bx-user-pin services__icon",
    modal1: "Increase customer loyalty and retention",
    modal2: "Increases productivity",
    modal3: "Retain users for a long time",
  },
];
